# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup Nim environment
      uses: jiro4989/setup-nim-action@v1.0.2
      with:
        nim-version: devel  # optional, default is stable

    - name: Nimble Refresh
      run: |
        export PATH=$HOME/.nimble/bin:$PATH
        nimble -y refresh

    - name: Nimble Install dependencies
      run: |
        export PATH=$HOME/.nimble/bin:$PATH
        nimble -y install requirementstxt libarchibi

    - name: Compile RELEASE Mode
      run: |
        export PATH=$HOME/.nimble/bin:$PATH
        nim c src/plz.nim

    - name: Strip Binary
      run: strip --strip-all src/plz

    - name: Run
      run: |
        src/plz --help
        src/plz --version
        src/plz --license
        src/plz --dump
